# Generated by Django 6.0.3 on 2026-04-12 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PythonAnalysis',
            fields=[
                ('analysis_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=200)),
                ('file_size_kb', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quality_classification', models.CharField(blank=True, max_length=50, null=True)),
                ('pep8_compliance', models.IntegerField(blank=True, null=True)),
                ('analysis_status', models.CharField(blank=True, max_length=10, null=True)),
                ('analysis_date', models.DateTimeField(blank=True, null=True)),
                ('analysis_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=150, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'python_analysis',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PythonMetrics',
            fields=[
                ('metrics_id', models.AutoField(primary_key=True, serialize=False)),
                ('lines_of_code', models.IntegerField(blank=True, null=True)),
                ('cyclomatic_complexity', models.IntegerField(blank=True, null=True)),
                ('functions_count', models.IntegerField(blank=True, null=True)),
                ('classes_count', models.IntegerField(blank=True, null=True)),
                ('imports_count', models.IntegerField(blank=True, null=True)),
                ('pep8_violations', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=150, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=150, null=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='analisis.pythonanalysis')),
            ],
            options={
                'db_table': 'python_metrics',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UploadBatch',
            fields=[
                ('batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_files', models.IntegerField(blank=True, null=True)),
                ('upload_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=150, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=150, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'upload_batch',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='pythonanalysis',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='analisis.uploadbatch'),
        ),
    ]
