sonar.projectKey=python-metrics-system-fronted
sonar.projectName=python-metrics-system-fronted
sonar.projectVersion=1.0

# Codigo fuente Python del proyecto
sonar.sources=src
sonar.sourceEncoding=UTF-8

# Analizar solo archivos Python
sonar.language=js

# Excluir artefactos no relevantes
sonar.exclusions=node_modules/**,build/**,public/**,**/*.test.js,**/*.test.jsx

# Tests
# sonar.tests=apps
# sonar.test.inclusions=**/tests/**/*.py,**/test_*.py