# Generated by Django 6.0.3 on 2026-04-12 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='miusuario',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('client', 'Cliente')], default='client', max_length=10),
        ),
        migrations.AlterField(
            model_name='miusuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
