# Generated by Django 6.0.3 on 2026-04-12 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('bitacora_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_dato', models.CharField(help_text='Nombre de la tabla/entidad afectada', max_length=255)),
                ('tipo_movimiento', models.CharField(help_text='INSERT, UPDATE, DELETE', max_length=20)),
                ('accion', models.CharField(blank=True, help_text='Descripción de la acción', max_length=255, null=True)),
                ('valor_antes', models.JSONField(blank=True, help_text='JSON del estado anterior del registro', null=True)),
                ('valor_despues', models.JSONField(blank=True, help_text='JSON del estado posterior del registro', null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('host_origen', models.CharField(blank=True, help_text='Host desde donde se originó la acción', max_length=255, null=True)),
                ('usuario', models.CharField(blank=True, help_text='Usuario de la app (email del JWT)', max_length=255, null=True)),
                ('es_accion_bd', models.BooleanField(default=False, help_text='True si la acción fue directamente en BD, no vía API')),
                ('usuario_bd', models.CharField(blank=True, help_text='Usuario de BD que ejecutó la acción (si no fue api_user)', max_length=255, null=True)),
            ],
            options={
                'db_table': 'bitacora',
                'ordering': ['-fecha_hora'],
                'managed': True,
            },
        ),
    ]
